SolutionE-RH_v1.5/SolutionE-RH_v1.5/Models/DEMANDE_CONGE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionE_RH_v1._5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDE_CONGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEMANDE_CONGE()
        {
            this.AVIS_DM = new HashSet<AVIS_DM>();
        }
    
        public decimal ID_DEMANDE { get; set; }
        public string MATRECULE { get; set; }
        public string PERIODE { get; set; }
        public System.DateTime DATE_DEBUT { get; set; }
        public string FICHIER_JUST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AVIS_DM> AVIS_DM { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Controllers/DEMANDE_CONGEController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SolutionE_RH_v1._5.Models;

namespace SolutionE_RH_v1._5.Controllers
{
    public class DEMANDE_CONGEController : Controller
    {
        private E_RHEntities1 db = new E_RHEntities1();

        // GET: DEMANDE_CONGE
        public ActionResult Index()
        {
            var dEMANDE_CONGE = db.DEMANDE_CONGE.Include(d => d.EMPLOYEE);
            return View(dEMANDE_CONGE.ToList());
        }

        // GET: DEMANDE_CONGE/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEMANDE_CONGE dEMANDE_CONGE = db.DEMANDE_CONGE.Find(id);
            if (dEMANDE_CONGE == null)
            {
                return HttpNotFound();
            }
            return View(dEMANDE_CONGE);
        }

        // GET: DEMANDE_CONGE/Create
        public ActionResult Create()
        {
            ViewBag.MATRECULE = new SelectList(db.EMPLOYEEs, "MATRECULE", "CIN");
            return View();
        }

        // POST: DEMANDE_CONGE/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_DEMANDE,MATRECULE,PERIODE,DATE_DEBUT,FICHIER_JUST")] DEMANDE_CONGE dEMANDE_CONGE, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
           


                    var fileName = Path.GetFileName(file.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                    file.SaveAs(path);

                    dEMANDE_CONGE.FICHIER_JUST = fileName;
                    db.DEMANDE_CONGE.Add(dEMANDE_CONGE);
                        db.SaveChanges();
                }

                
                return RedirectToAction("Index");
            }

            ViewBag.MATRECULE = new SelectList(db.EMPLOYEEs, "MATRECULE", "CIN", dEMANDE_CONGE.MATRECULE);
            return View(dEMANDE_CONGE);
        }

        // GET: DEMANDE_CONGE/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEMANDE_CONGE dEMANDE_CONGE = db.DEMANDE_CONGE.Find(id);
            if (dEMANDE_CONGE == null)
            {
                return HttpNotFound();
            }
            ViewBag.MATRECULE = new SelectList(db.EMPLOYEEs, "MATRECULE", "CIN", dEMANDE_CONGE.MATRECULE);
            return View(dEMANDE_CONGE);
        }

        // POST: DEMANDE_CONGE/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_DEMANDE,MATRECULE,DATE_ENVOI,PERIODE,DATE_DEBUT,FICHIER_JUST")] DEMANDE_CONGE dEMANDE_CONGE)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dEMANDE_CONGE).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MATRECULE = new SelectList(db.EMPLOYEEs, "MATRECULE", "CIN", dEMANDE_CONGE.MATRECULE);
            return View(dEMANDE_CONGE);
        }

        // GET: DEMANDE_CONGE/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DEMANDE_CONGE dEMANDE_CONGE = db.DEMANDE_CONGE.Find(id);
            if (dEMANDE_CONGE == null)
            {
                return HttpNotFound();
            }
            return View(dEMANDE_CONGE);
        }

        // POST: DEMANDE_CONGE/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            DEMANDE_CONGE dEMANDE_CONGE = db.DEMANDE_CONGE.Find(id);
            db.DEMANDE_CONGE.Remove(dEMANDE_CONGE);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Views/DEMANDE_CONGE_/Create.cshtml
@model SolutionE_RH_v1._5.Models.DEMANDE_CONGE

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<header>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    </header>
    <script>


        $(document).ready(function () {
            $("#DATE_DEBUT").datepicker({
                dateFormat: "dd-mm-yy",
                minDate: -0,
                maxDate: "+0M +0D"

            });
        });
    </script>*@
<!-- Code to wire up your DatePicker -->
<script type="text/javascript">
    $(function () {
        // This will make every element with the class "date-picker" into a DatePicker element
        $('.date-picker').datepicker();
    })
</script>
<center><h2>Demande de congé</h2></center>

@using (Html.BeginForm("Create", "DEMANDE_CONGE", FormMethod.Post, new { enctype = "multipart/form-data" }))

{


    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MATRECULE, "MATRECULE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MATRECULE", null, htmlAttributes: new { @class = "form-control1" })
                @Html.ValidationMessageFor(model => model.MATRECULE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PERIODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PERIODE, new { htmlAttributes = new { @class = "form-control1" } })
                @Html.ValidationMessageFor(model => model.PERIODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_DEBUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_DEBUT, new { htmlAttributes = new { @class = "date-picker" , style = "border: 1px solid #e0e0e0;padding: 5px 8px;color: #616161;background: #fff;box - shadow: none !important; width:100%;font - size: 0.85em;font - weight: 300;height: 40px;border - radius: 0;-webkit - appearance: none; " } })
                                @Html.ValidationMessageFor(model => model.DATE_DEBUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FICHIER_JUST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("file", "", new { type = "file" }) <br />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Views/DEMANDE_CONGE_/Delete.cshtml
@model SolutionE_RH_v1._5.Models.DEMANDE_CONGE

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DEMANDE_CONGE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATE_ENVOI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_ENVOI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERIODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERIODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATE_DEBUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_DEBUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FICHIER_JUST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FICHIER_JUST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMPLOYEE.CIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMPLOYEE.CIN)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Views/DEMANDE_CONGE_/Details.cshtml
@model SolutionE_RH_v1._5.Models.DEMANDE_CONGE

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DEMANDE_CONGE</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DATE_ENVOI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_ENVOI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERIODE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERIODE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATE_DEBUT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATE_DEBUT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FICHIER_JUST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FICHIER_JUST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EMPLOYEE.CIN)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EMPLOYEE.CIN)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_DEMANDE }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Views/DEMANDE_CONGE_/Edit.cshtml
@model SolutionE_RH_v1._5.Models.DEMANDE_CONGE

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DEMANDE_CONGE</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_DEMANDE)

        <div class="form-group">
            @Html.LabelFor(model => model.MATRECULE, "MATRECULE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MATRECULE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MATRECULE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_ENVOI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_ENVOI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATE_ENVOI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PERIODE, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PERIODE, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PERIODE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATE_DEBUT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATE_DEBUT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATE_DEBUT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FICHIER_JUST, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FICHIER_JUST, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FICHIER_JUST, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SolutionE-RH_v1.5/SolutionE-RH_v1.5/Views/DEMANDE_CONGE_/Index.cshtml
@model IEnumerable<SolutionE_RH_v1._5.Models.DEMANDE_CONGE>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DATE_ENVOI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PERIODE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DATE_DEBUT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FICHIER_JUST)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EMPLOYEE.CIN)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DATE_ENVOI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PERIODE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DATE_DEBUT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FICHIER_JUST)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EMPLOYEE.CIN)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_DEMANDE }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_DEMANDE }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_DEMANDE })
        </td>
    </tr>
}

</table>